universe = vanilla

log = $(CLUSTER).log
output = $(CLUSTER).process.out
error = $(CLUSTER).process.err

requirements = (OpSysMajorVer == 7) && (Target.HasGluster == true)

transfer_input_files  = python.tar.gz, quast-4.6.1.tar.gz
executable = qc_check.sh  

# Indicate all files that need to go into the interactive job session,
#  including any tar files that you prepare

#  It's still important to request enough computing resources. The below 
#  values are a good starting point, but consider your file sizes for an
#  estimate of "disk" and use any other information you might have
#  for "memory" and/or "cpus".

request_cpus =2
request_memory =6GB
request_disk =150GB

queue
