universe = vanilla
# Name the log file:
log = interactive.log

# Name the files where standard output and error should be saved:
output = process.out
error = process.err

# If you wish to compile code, you'll need the below lines. 
#  Otherwise, LEAVE THEM OUT if you just want to interactively test!
requirements = (OpSys == "LINUX") && (OpSysMajorVer == 7) && (Target.HasGluster == true)


# Indicate all files that need to go into the interactive job session,
# including any tar files that you prepared:
transfer_input_files = jre-8u144-linux-x64.tar.gz, Trimmomatic-0.36.zip, fastqc_v0.11.5.zip, Trimmomatic_CMD_loop_nested 

# It's still important to request enough computing resources. The below 
#  values are a good starting point, but consider your file sizes for an
#  estimate of "disk" and use any other information you might have
#  for "memory" and/or "cpus".
request_cpus = 2
request_memory = 8GB
request_disk = 250GB

queue
