#!/bin/sh

#This script was to be used to trim metagenome 202 using a particular Q score cut-off and run fastQC on it
#filenames are hardcoded so a number of different lines need to be changed to work with other metagenomes
#was used for testing only and not frequent use

#Untar java install and move it into directory 
tar -xzf jre-8u144-linux-x64.tar.gz
export PATH=$(pwd)/jre1.8.0_144/bin:$PATH

cp /mnt/gluster/tdberry/202_deinterleaved.tar.gz ./
tar -xvzf 202_deinterleaved.tar.gz  

#Unzip FastQC
unzip fastqc_v0.11.5.zip

#Make fastqc executable
cd FastQC
chmod +x fastqc

#Go back to home and put fastqc in path
cd ../
export PATH=$(pwd)/FastQC:$PATH

#Unzip Trimmomatic
unzip Trimmomatic-0.36.zip

#Command calls trimmomatic on files test_outputs.pe*.fq and names outputs, and specifies trimming parameters. Also includes path to sequencing adapters to remove.
java -jar ./Trimmomatic-0.36/trimmomatic-0.36.jar PE -phred33 202_MG_QC.fastq.gz.pe1.fq 202_MG_QC.fastq.gz.pe2.fq test2_202_1_paired.fq.gz test2_202_1_unpaired.fq.gz test2_202_2_paired.fq.gz test2_202_2_unpaired.fq.gz ILLUMINACLIP:./Trimmomatic-0.36/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:25 MINLEN:36

mkdir test2
cp test2_202* test2
cd test2
../FastQC/fastqc test2_202*

cd ../
tar -czf 202_trim_test2.tar.gz test2
cp 202_trim_test2.tar.gz /mnt/gluster/tdberry/ 

#Remove extraneous files
rm -rf *.zip *.tar.gz *.fq 
