universe = vanilla

log = $(CLUSTER).log
output = $(CLUSTER).process.out
error = $(CLUSTER).process.err

requirements = (OpSysMajorVer == 7) && (Target.HasGluster == true)

executable = TransferringJGIfiles.sh

# Indicate all files that need to go into the interactive job session,
#  including any tar files that you prepare

#  It's still important to request enough computing resources. The below 
#  values are a good starting point, but consider your file sizes for an
#  estimate of "disk" and use any other information you might have
#  for "memory" and/or "cpus".

request_cpus = 1
request_memory = 1GB
request_disk = 300GB

queue
