universe = vanilla
# Name the log file:
log = log

# Name the files where standard output and error should be saved:
output = 242.out
error = 242.err

# If you wish to compile code, you'll need the below lines. 
#  Otherwise, LEAVE THEM OUT if you just want to interactively test!
requirements = (OpSys == "LINUX") && (OpSysMajorVer == 7) && (Target.HasGluster == true)

# Indicate all files that need to go into the interactive job session,
#  including any tar files that you prepared:

executable = 242_dl_parse.sh
transfer_input_files = python.tar.gz, parse.py

# It's still important to request enough computing resources. The below 
#  values are a good starting point, but consider your file sizes for an
#  estimate of "disk" and use any other information you might have
#  for "memory" and/or "cpus".
request_cpus = 1
request_memory = 1GB
request_disk = 150GB

queue
